name: Automated Test Suite

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - 'artifacts/**'
      - '*.md'
      - '.gitignore'
  schedule:
    # Run nightly at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Test Suite to Run'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - ui
        - api
      browser:
        description: 'Browser for UI Tests'
        required: false
        default: 'chrome'
        type: choice
        options:
        - chrome
        - firefox
        - edge

env:
  MAVEN_OPTS: -Xmx2048m
  JAVA_VERSION: '21'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      test-suites: ${{ steps.determine-suites.outputs.suites }}
      timestamp: ${{ steps.timestamp.outputs.timestamp }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for automation commits
        id: check-commit
        run: |
          if [[ "${{ github.event.head_commit.message }}" =~ ^(automation|auto|ci|build):.* ]]; then
            echo "skip=true" >> $GITHUB_OUTPUT
            echo "Skipping automation commit: ${{ github.event.head_commit.message }}"
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Generate Timestamp
        id: timestamp
        run: echo "timestamp=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT

      - name: Determine Test Suites
        id: determine-suites
        run: |
          if [ "${{ github.event.inputs.test_suite }}" == "ui" ]; then
            echo "suites=[\"ui\"]" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.inputs.test_suite }}" == "api" ]; then
            echo "suites=[\"api\"]" >> $GITHUB_OUTPUT
          else
            echo "suites=[\"ui\", \"api\"]" >> $GITHUB_OUTPUT
          fi

      - name: Exit if automation commit
        if: steps.check-commit.outputs.skip == 'true'
        run: |
          echo "Skipping CI for automation commit"
          exit 78

  ui-tests:
    needs: setup
    if: contains(fromJson(needs.setup.outputs.test-suites), 'ui')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox]
      fail-fast: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: maven

    

      - name: Setup Chrome
        if: matrix.browser == 'chrome'
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

      - name: Setup Firefox
        if: matrix.browser == 'firefox'
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: latest

      - name: Configure Git User
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Create Screenshots Directory
        run: mkdir -p artifacts/screenshots

      - name: Run UI Tests
        run: |
          mvn clean test -Dsuite=ui -Dbrowser=${{ matrix.browser }} \
            -Dparallel=methods -DthreadCount=3 \
            -Dtestng.dtd.http=true \
            -Dmaven.test.failure.ignore=true
        env:
          BROWSER: ${{ matrix.browser }}
          HEADLESS: true
          SCREENSHOT_ON_FAILURE: true

      - name: Generate UI Test Reports
        if: always()
        run: |
          mvn surefire-report:report-only
          mvn site -DgenerateReports=false

      - name: Upload UI Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-results-${{ matrix.browser }}-${{ needs.setup.outputs.timestamp }}
          path: |
            target/surefire-reports/
            target/site/
            artifacts/screenshots/
            artifacts/reports/
          retention-days: 30

      - name: Upload Screenshots on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ui-screenshots-failure-${{ matrix.browser }}-${{ needs.setup.outputs.timestamp }}
          path: artifacts/screenshots/
          retention-days: 7

  api-tests:
    needs: setup
    if: contains(fromJson(needs.setup.outputs.test-suites), 'api')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: maven

      - name: Configure Git User
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Run API Tests
        run: |
          mvn clean test -Dsuite=api \
            -Dparallel=methods -DthreadCount=5 \
            -Dtestng.dtd.http=true \
            -Dmaven.test.failure.ignore=true

      - name: Generate API Test Reports
        if: always()
        run: |
          mvn surefire-report:report-only
          mvn site -DgenerateReports=false

      - name: Upload API Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results-${{ needs.setup.outputs.timestamp }}
          path: |
            target/surefire-reports/
            target/site/
            artifacts/api/
            artifacts/reports/
          retention-days: 30

  analytics-update:
    needs: [setup, ui-tests, api-tests]
    if: always() && (needs.ui-tests.result != 'cancelled' || needs.api-tests.result != 'cancelled')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: maven

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: downloaded-artifacts/

      - name: Call Analytics Endpoint
        run: |
          curl -X POST "${{ secrets.ANALYTICS_ENDPOINT_URL || 'http://localhost:8080/api/analytics/refresh' }}" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.ANALYTICS_TOKEN || 'default-token' }}" \
            -d '{
              "timestamp": "${{ needs.setup.outputs.timestamp }}",
              "trigger": "${{ github.event_name }}",
              "branch": "${{ github.ref_name }}",
              "commit": "${{ github.sha }}",
              "ui_result": "${{ needs.ui-tests.result }}",
              "api_result": "${{ needs.api-tests.result }}"
            }' \
            --fail-with-body \
            --retry 3 \
            --retry-delay 5 || echo "Analytics endpoint call failed, continuing..."

  consolidate-reports:
    needs: [setup, ui-tests, api-tests]
    if: always() && (needs.ui-tests.result != 'cancelled' || needs.api-tests.result != 'cancelled')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download All Test Results
        uses: actions/download-artifact@v4
        with:
          path: all-results/

      - name: Consolidate Reports
        run: |
          mkdir -p consolidated-reports
          find all-results/ -name "*.html" -exec cp {} consolidated-reports/ \;
          find all-results/ -name "*.xml" -exec cp {} consolidated-reports/ \;
          find all-results/ -name "*.json" -exec cp {} consolidated-reports/ \;
          
          # Create summary report
          echo "# Test Execution Summary - ${{ needs.setup.outputs.timestamp }}" > consolidated-reports/README.md
          echo "" >> consolidated-reports/README.md
          echo "**Trigger:** ${{ github.event_name }}" >> consolidated-reports/README.md
          echo "**Branch:** ${{ github.ref_name }}" >> consolidated-reports/README.md
          echo "**Commit:** ${{ github.sha }}" >> consolidated-reports/README.md
          echo "**UI Tests:** ${{ needs.ui-tests.result }}" >> consolidated-reports/README.md
          echo "**API Tests:** ${{ needs.api-tests.result }}" >> consolidated-reports/README.md
          echo "**Timestamp:** $(date)" >> consolidated-reports/README.md

      - name: Upload Consolidated Reports
        uses: actions/upload-artifact@v4
        with:
          name: consolidated-test-reports-${{ needs.setup.outputs.timestamp }}
          path: consolidated-reports/
          retention-days: 90

  notification:
    needs: [setup, ui-tests, api-tests, analytics-update]
    if: always()
    runs-on: ubuntu-latest

    steps:
      - name: Notify on Failure
        if: needs.ui-tests.result == 'failure' || needs.api-tests.result == 'failure'
        run: |
          echo "Tests failed! Check the artifacts for detailed reports."
          echo "UI Tests: ${{ needs.ui-tests.result }}"
          echo "API Tests: ${{ needs.api-tests.result }}"
